### ISSUE TITLE
3.0.0 release CheckList

### ISSUE THREAD

**Issue by ykeara** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#120]
# Release CheckList for 3.0.0

### Features to add
- [x] #65 - partially implemented, UI to add yet. - Kung
- [x] #111 - Username223
- [x] #102 - Need to decide what they should be, and as well as wait for #65 and #111 

### Testing

- [x] General testing of a release candidate 3.0.0 build
- [x] Targeted testing of New features
  - [x] PTT
  - [x] various space moving features
  - [x] chaperone warnings

### Documentation

- [x] #72 Ykeara
- [x] #109  Ykeara
- [x] Video explaining new features - Kung

### Bugs

- [x] #123 

### Questionable?

- [x] #41 do we need more formal documentation in code, or keep the somewhat informal process we have now?

**Comment by ykeara** [comment]
#72 Will be resolved via PR #126 , other than that testing is on-going no major issues so-far.

**Comment by ykeara** [comment]
ready for launch thus closing.
