### ISSUE TITLE
Meta: Upgrade to Qt6

### ISSUE THREAD

**Issue by RTUnreal** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#656]
Upgrade OVRAS to Qt6 and start modernizing the app for future versions. It also enables the app to use graphics API's other than 

**Steps to take**
- [ ] Upgrade the application to Qt6
   - [ ] Use cmake instead of qmake as qmake is somewhat deprecated
   - [ ] find alternative ways to test and build the Qt6 libraries with actions, as binaries are not provided anymore by Qt (e.g. [jurplel/install-qt-action](https://jurplel/install-qt-action))
   - [ ] document how to build from source
   - [ ] replace easylogging++ with Qt6's native logging system

This list is not exhaustive and might/will be extended.
